### PR TITLE
feat: add the ability to have each markdown file as individual slideshow

### PR DESCRIPTION
**Pull request by cindrmon**
- Refactor entire folder structure
- Use `sass` and `libsass` to compile for custom styling
- each new content markdown file can now be an individual slideshow, which means you can make multiple slideshows in one static website!
- main index page

TODO:
- add subdirectory listings

### CODE REVIEW

**Comment by cindrmon** [comment]
i've added the ability to make multiple slideshows for each markdown content file you make. I don't know if that's a plus for you, or this isn't really your intention with this theme. I totally understand if you could reject it, but I just got inspired in making this pull request since someone had already made a hugo remarkjs theme.

**Comment by sporto** [comment]
@cindrmon thanks, are you still working on this PR?

**Comment by cindrmon** [comment]
> @cindrmon thanks, are you still working on this PR?

yea, im actually supposed to add the listings for each directory to show all the slides of that directory. btw, how was it so far?

**Comment by cindrmon** [comment]
hi! already added the subdirectory listings for these next commits, would want to know if is good. i might not add a lot of stuff for a while, since that's like, all the idea features i have for this, but yea, still pretty barebones.

**Comment by sporto** [comment]
Great, thanks

**Comment by sporto** [comment]
@cindrmon I reverted to use plain CSS, tried SASS with my installation of hugo and got this error https://github.com/gohugoio/hugo/issues/7182 
So I feel that using SASS is more complex that it needs to be for a theme as we are imposing using hugo "extended version".

**Comment by cindrmon** [comment]
oh yea that. i forgot you needed `hugo-extended` instead of `hugo` for sass, but its fine either way. I'll just keep my own fork as the one with sass support, and requires `hugo-extended` as a dependency.

**Comment by cindrmon** [comment]
i'm just gonna keep my fork and work on it separately from this project from now on, since i'd be using sass more often than css.

**Pull request merged**
